In [13]:
# Importing necessary libraries

import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import *
from sklearn import svm
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import Imputer
import sklearn
import pandas
import random
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
# Reading in file 

#raw_data = pandas.read_csv('contactid_08_01_18download.csv', encoding="utf-8")
##raw_data

## This will show us (# of rows, # of columns)
#raw_data.shape

In [15]:
#raw_data

In [16]:
updated_raw_data = pandas.read_csv('contactid_08_29_18.csv', encoding="utf-8")

updated_raw_data.shape

(18265, 57)

In [17]:
updated_raw_data

,subjectid,scale,age,black,tot.child,health.sr,diag,shelter,recstay.yrs,ageinc,...,Number of outgoing calls at night,Any night incoming call,Any night outgoing call,Min days between calls,Max days between calls,Total number of texts,Any night text,Number of texts at night,Min days between texts,Max days between texts
0,1003,4,31,0,1.0,1,0,0,2.115068,19.000000,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.000000,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
2,1005,5,26,0,0.0,1,0,0,1.210959,19.000000,...,0.0,1.0,0.0,NaN,NaN,1,0,0,NaN,NaN
3,1006,5,28,1,0.0,3,0,0,0.887671,21.000000,...,NaN,NaN,NaN,NaN,NaN,1,0,0,NaN,NaN
4,1007,1,38,1,1.0,2,1,0,3.638356,21.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
5,1101,5,22,1,1.0,3,0,0,2.057534,20.000000,...,0.0,0.0,0.0,22.0,22.0,0,0,0,NaN,NaN
6,1102,4,32,1,0.0,2,0,0,5.772603,26.000000,...,0.0,1.0,0.0,1.0,1.0,0,0,0,NaN,NaN
7,1103,3,33,1,0.0,4,0,0,13.375342,19.775343,...,1.0,1.0,1.0,NaN,NaN,0,0,0,NaN,NaN
8,1106,5,24,1,0.0,1,0,0,4.509589,19.512329,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
9,1107,4,33,1,2.0,2,0,0,2.953425,30.000000,...,NaN,NaN,NaN,NaN,NaN,2,0,0,12.0,12.0
10,1108,4,27,1,0.0,1,0,0,6.800000,20.561644,...,11.0,0.0,1.0,1.0,6.0,0,0,0,NaN,NaN
11,1201,4,26,1,2.0,1,1,0,4.298630,22.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
12,1202,5,24,1,0.0,1,0,0,2.890411,21.241097,...,NaN,NaN,NaN,NaN,NaN,7,1,7,NaN,NaN
13,1203,5,28,1,1.0,3,0,0,0.421918,27.764383,...,1.0,0.0,1.0,NaN,NaN,0,0,0,NaN,NaN
14,1204,5,34,1,2.0,4,0,0,0.547945,14.000000,...,12.0,1.0,1.0,1.0,23.0,10,1,4,1.0,31.0
15,1205,4,33,1,1.0,4,0,0,5.010959,18.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
16,1206,5,54,1,5.0,3,0,0,7.284932,30.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
17,1207,5,37,1,1.0,3,0,0,5.882192,28.000000,...,23.0,1.0,1.0,1.0,9.0,16,1,5,4.0,11.0
18,1208,5,54,1,2.0,4,1,0,12.873973,41.695889,...,1.0,0.0,1.0,NaN,NaN,0,0,0,NaN,NaN
19,1209,5,58,1,3.0,4,0,0,2.197260,21.000000,...,24.0,1.0,1.0,1.0,3.0,0,0,0,NaN,NaN
20,1210,4,25,1,0.0,2,0,0,0.824658,20.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
21,1212,2,54,1,4.0,4,0,0,5.106849,37.000000,...,0.0,1.0,0.0,1.0,24.0,0,0,0,NaN,NaN
22,1213,5,39,1,5.0,4,0,0,2.169863,22.000000,...,0.0,0.0,0.0,1.0,1.0,0,0,0,NaN,NaN
23,1216,4,39,1,1.0,1,0,0,0.854795,19.000000,...,0.0,1.0,0.0,1.0,1.0,0,0,0,NaN,NaN
24,1218,5,22,0,0.0,1,1,0,0.364384,21.789042,...,NaN,NaN,NaN,NaN,NaN,6,0,0,2.0,2.0
25,1301,3,46,1,1.0,2,0,0,3.216438,33.000000,...,0.0,1.0,0.0,1.0,1.0,0,0,0,NaN,NaN
26,1302,3,48,1,3.0,2,0,0,1.079452,18.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
27,1304,4,33,1,1.0,4,0,0,15.306849,18.610958,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
28,1305,2,34,1,0.0,1,1,0,2.736986,21.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
29,1307,4,48,1,2.0,1,1,1,13.295891,23.000000,...,1.0,0.0,1.0,6.0,6.0,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18235,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,4.0,1.0,1.0,1.0,9.0,2,0,0,1.0,1.0
18236,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,NaN,NaN,NaN,NaN,NaN,6,1,1,13.0,19.0
18237,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,1.0,0.0,1.0,5.0,5.0,0,0,0,NaN,NaN
18238,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
18239,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
18240,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,1.0,1.0,1.0,2.0,8.0,0,0,0,NaN,NaN
18241,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
18242,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
18243,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,2.0,0.0,1.0,1.0,15.0,0,0,0,NaN,NaN
18244,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,1.0,1.0,1.0,1.0,27.0,0,0,0,NaN,NaN
18245,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
18246,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
18247,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,3.0,0.0,1.0,1.0,17.0,1,0,0,NaN,NaN
18248,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,1.0,0.0,1.0,1.0,26.0,0,0,0,NaN,NaN
18249,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
18250,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,NaN,NaN,NaN,NaN,NaN,1,1,1,NaN,NaN
18251,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
18252,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,0.0,0.0,0.0,3.0,41.0,0,0,0,NaN,NaN
18253,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,8.0,1.0,1.0,1.0,12.0,237,1,63,1.0,8.0
18254,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,6.0,1.0,1.0,1.0,15.0,3,0,0,NaN,NaN
18255,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,3.0,1.0,1.0,1.0,18.0,2,1,2,1.0,1.0
18256,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
18257,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,NaN,NaN,NaN,NaN,NaN,10,1,6,9.0,49.0
18258,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,NaN,NaN,NaN,NaN,NaN,1,0,0,NaN,NaN
18259,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
18260,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,0.0,0.0,0.0,NaN,NaN,0,0,0,NaN,NaN
18261,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,6.0,0.0,1.0,1.0,44.0,2,0,0,NaN,NaN
18262,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,NaN,NaN,NaN,NaN,NaN,11,1,7,1.0,1.0
18263,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,1.0,1.0,1.0,1.0,19.0,10,1,2,1.0,20.0
18264,9015,3,46,1,3.0,1,0,1,8.589041,24.000000,...,9.0,1.0,1.0,1.0,21.0,1,1,1,NaN,NaN

In [18]:
updated_raw_data_filled = updated_raw_data.loc[updated_raw_data['Min days between calls'].fillna(0)]

In [19]:
updated_raw_data_filled

,subjectid,scale,age,black,tot.child,health.sr,diag,shelter,recstay.yrs,ageinc,...,Number of outgoing calls at night,Any night incoming call,Any night outgoing call,Min days between calls,Max days between calls,Total number of texts,Any night text,Number of texts at night,Min days between texts,Max days between texts
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
2,1005,5,26,0,0.0,1,0,0,1.210959,19.0,...,0.0,1.0,0.0,NaN,NaN,1,0,0,NaN,NaN
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
22,1213,5,39,1,5.0,4,0,0,2.169863,22.0,...,0.0,0.0,0.0,1.0,1.0,0,0,0,NaN,NaN
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
6,1102,4,32,1,0.0,2,0,0,5.772603,26.0,...,0.0,1.0,0.0,1.0,1.0,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
5,1101,5,22,1,1.0,3,0,0,2.057534,20.0,...,0.0,0.0,0.0,22.0,22.0,0,0,0,NaN,NaN
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
2,1005,5,26,0,0.0,1,0,0,1.210959,19.0,...,0.0,1.0,0.0,NaN,NaN,1,0,0,NaN,NaN
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
3,1006,5,28,1,0.0,3,0,0,0.887671,21.0,...,NaN,NaN,NaN,NaN,NaN,1,0,0,NaN,NaN
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
0,1003,4,31,0,1.0,1,0,0,2.115068,19.0,...,NaN,NaN,NaN,NaN,NaN,32,1,17,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0
1,1004,0,30,0,0.0,5,0,1,1.367123,27.0,...,4.0,1.0,1.0,2.0,2.0,14,1,12,1.0,4.0

In [20]:
# We only want to consider data in which the "Close" column has data
# so that is the first thing we filter and we train/test on that new DataFrame

dfclean = updated_raw_data.loc[updated_raw_data['close'].notnull()]
#dfclean

# This will show us (# of rows, # of columns)
dfclean.shape

(2869, 57)

In [21]:
# Now we look over the workable data and see how clean it is

num_of_cells = dfclean.shape[0]*dfclean.shape[1]
num_of_cells

163533

In [22]:
# We look at all the columns with NaN values

df_null_columns = ((dfclean.isnull().sum()/dfclean.shape[0])*100).round(decimals=2).astype(str) + '%'
df_null_columns.to_frame('nulls')
#df_null_columns

                                                   nulls
subjectid                                           0.0%
scale                                               0.0%
age                                                 0.0%
black                                               0.0%
tot.child                                          0.03%
health.sr                                           0.0%
diag                                                0.0%
shelter                                             0.0%
recstay.yrs                                         0.0%
ageinc                                              0.0%
anyfjob                                             0.0%
prevfelony                                          0.0%
preconvict_num                                      0.0%
preinc_num                                          0.0%
anywork                                             0.0%
rel_single                                          0.0%
rel_partner                                         0.0%
rel_married                                         0.0%
educ_lessHS                                         0.0%
educ_HS                                             0.0%
educ_somecol                                        0.0%
educ_col                                            0.0%
Contact.ID                                          0.0%
cat                                                 0.0%
svy_contact                                         0.0%
empstatus                                          9.27%
jailprison                                        10.46%
close                                               0.0%
baseline_flag                                       0.0%
dup                                                 0.0%
reinstall_flag1                                     0.0%
reinstall_flag2                                     0.0%
phonesurvey                                         0.0%
Total number of calls                               0.0%
Total duration of calls                             0.0%
Total incoming calls                                0.0%
Total outgoing calls                                0.0%
Total number of missed calls                        0.0%
Total number of incoming calls, excluding missed    0.0%
Proportion of incoming calls answered               0.0%
0 to 1, =1 perfect reciprocity                      0.0%
Proportion of calls incoming                        0.0%
Duration of incoming calls                          0.0%
Duration of outgoing calls                          0.0%
Total number of night calls                         0.0%
Any night call                                      0.0%
Number of incoming calls at night                   0.0%
Number of outgoing calls at night                   0.0%
Any night incoming call                             0.0%
Any night outgoing call                             0.0%
Min days between calls                            31.37%
Max days between calls                            31.37%
Total number of texts                               0.0%
Any night text                                      0.0%
Number of texts at night                            0.0%
Min days between texts                            73.54%
Max days between texts                            73.54%

In [23]:
# We also look at all the rows with at least one NaN value

df_null_rows = dfclean.isnull().sum(axis=1)
# df_null_rows

In [24]:
# The percentage of rows missing at least one value would be

(((df_null_rows!=0).sum()/(df_null_rows.shape[0]))*100).round(decimals=2).astype(str) + '%'

'78.84%'

In [25]:
# And lastly we consider missing cells in relation to all total cells 

num_of_missing_cells = (dfclean.isnull().sum()).sum()
((num_of_missing_cells/num_of_cells)*100).round(decimals=2).astype(str) + '%'

'4.03%'

In [26]:
#Now we begin to train/test the data, in hopes of being able to most accurately predict the closeness column for the original file

In [27]:
# We begin by looking at 2 different introductory Models that helps us visualize the data

#GradientBoostingClassifier
#GradientBoostingRegressor
updated_raw_data.loc[raw_data['close'].notnull()]

# Before we begin with these Models, we need to format the data in a manner in which we can work with
dfcleanX = dfclean.fillna(-1)
# dfcleanX

In [28]:
# We filter out the specific columns we are interested in
xdata = dfcleanX[['jailprison' ,'Total number of calls',
'Total duration of calls',
'Total incoming calls',
'Total outgoing calls',
'Total number of missed calls',
'Total number of incoming calls, excluding missed',
'Proportion of incoming calls answered',
'Proportion of calls incoming',
'Duration of incoming calls',
'Duration of outgoing calls',
'Total number of night calls',
'Any night call',
'Number of incoming calls at night',
'Number of outgoing calls at night',
'Any night incoming call',
'Any night outgoing call',
'Min days between calls',
'Max days between calls',
'Total number of texts',
'Any night text',
'Number of texts at night',
'Min days between texts',
'Max days between texts']].values
all_cols = set(dfcleanX.columns.values)
all_cols.difference(['Contact.ID','close'])

{'0 to 1, =1 perfect reciprocity',
 'Any night call',
 'Any night incoming call',
 'Any night outgoing call',
 'Any night text',
 'Duration of incoming calls',
 'Duration of outgoing calls',
 'Max days between calls',
 'Max days between texts',
 'Min days between calls',
 'Min days between texts',
 'Number of incoming calls at night',
 'Number of outgoing calls at night',
 'Number of texts at night',
 'Proportion of calls incoming',
 'Proportion of incoming calls answered',
 'Total duration of calls',
 'Total incoming calls',
 'Total number of calls',
 'Total number of incoming calls, excluding missed',
 'Total number of missed calls',
 'Total number of night calls',
 'Total number of texts',
 'Total outgoing calls',
 'age',
 'ageinc',
 'anyfjob',
 'anywork',
 'baseline_flag',
 'black',
 'cat',
 'diag',
 'dup',
 'educ_HS',
 'educ_col',
 'educ_lessHS',
 'educ_somecol',
 'empstatus',
 'health.sr',
 'jailprison',
 'phonesurvey',
 'preconvict_num',
 'preinc_num',
 'prevfelony',
 'recstay.yrs',
 'reinstall_flag1',
 'reinstall_flag2',
 'rel_married',
 'rel_partner',
 'rel_single',
 'scale',
 'shelter',
 'subjectid',
 'svy_contact',
 'tot.child'}

In [ ]:
# We implement a random 80/20 split of the data to be used for train/test

random.seed = 0
indices = np.array(range(2869))
random.shuffle(indices)
num_train = int(len(indices)*0.8)
train_indices = indices[:num_train]
test_indices =indices[num_train+1:]

# namimg variables that will be used for training/testing
xtrain = xdata[train_indices]
xtest = xdata[test_indices]

# ravel creates 1d array
y = dfclean[['close']].values.ravel()
ytrain = y[train_indices]
ytest = y[test_indices]

In [ ]:
# GradientBoostingClassifier

def transform(ytrain):
    if ytrain < 20:
        return 0
    if ytrain < 40:
        return 1
    if ytrain < 60:
        return 2
    if ytrain < 80:
        return 3
    if ytrain < 100:
        return 4
    return 5


ytrainClassifier = [transform(i) for i in ytrain]
ytestClassifier = [transform(i) for i in ytest]
# ytestClassifier
# xtrain.shape,ytrain.shape
plt.hist(ytrainClassifier)

In [ ]:
GBclassifier = GradientBoostingClassifier().fit(xtrain,ytrainClassifier)

yhatClassifier = GBclassifier.predict(xtrain)
yhatClassifier

In [ ]:
yhatClassifier = GBclassifier.predict(xtest)
accuracy_score(ytestClassifier, yhatClassifier)
plt.hist(yhatClassifier)

In [ ]:
n_estimators = []
train_err = []
test_err = []

for n_estimator in range(1,30): #[1,2,3,4,5,10,20,50]:
    GBclassifier = GradientBoostingClassifier(n_estimators=n_estimator).fit(xtrain,ytrainClassifier)
    yhatClassifier = GBclassifier.predict(xtrain)
    n_estimators.append(n_estimator)
    train_err.append(accuracy_score(ytrainClassifier, yhatClassifier))
    test_err.append(accuracy_score(ytestClassifier, GBclassifier.predict(xtest)))
    
plt.plot(n_estimators, train_err, label="Train")
plt.plot(n_estimators, test_err, label="Test")
plt.legend()

In [ ]:
GBclassifier = GradientBoostingClassifier(n_estimators=20).fit(xtrain,ytrainClassifier)
plt.hist(ytestClassifier, label="True")
plt.hist(GBclassifier.predict(xtest), label="Predicted")
plt.legend()

In [ ]:
plt.scatter(ytrainClassifier, GBclassifier.predict(xtrain), label="Train")
plt.scatter(ytestClassifier, GBclassifier.predict(xtest), label="Test")
plt.legend()

In [ ]:
# GradientBoostingRegressor

In [ ]:
GBregressor = GradientBoostingRegressor().fit(xtrain,ytrain)
yhatRegressor = GBregressor.predict(xtrain)
yhatRegressor

In [ ]:
yhatRegressor = GBregressor.predict(xtest)
mean_squared_error(ytest, yhatRegressor)

In [ ]:
n_estimators = []
train_err = []
test_err = []

for n_estimator in range(1,50): #[1,2,3,4,5,10,20,50]:
    GBregressor = GradientBoostingRegressor(n_estimators=n_estimator).fit(xtrain,ytrain)
    yhatRegressor = GBregressor.predict(xtrain)
    n_estimators.append(n_estimator)
    train_err.append(mean_squared_error(ytrain, yhatRegressor))
    test_err.append(mean_squared_error(ytest, GBregressor.predict(xtest)))
    
plt.plot(n_estimators, train_err, label="Train")
plt.plot(n_estimators, test_err, label="Test")
plt.legend()

In [ ]:
GBregressor = GradientBoostingRegressor(n_estimators=30).fit(xtrain,ytrain)
plt.hist(GBregressor.predict(xtest), label="Predicted")
plt.hist(ytest, label="True")
plt.legend()

In [ ]:
plt.scatter(ytrain, GBregressor.predict(xtrain), label="Train")
plt.scatter(ytest, GBregressor.predict(xtest), label="Test")
plt.legend()

In [ ]:
# We finally look at 2 different Advanced Models that helps us visualize the data
# SVR
# MLPRegressor
# Before we begin with these Models, we need to format the data in a manner in which we can work with

In [ ]:
# Imputer and formatting data
# Before we begin with these Models, we need to format the data in a manner in which we can work with, but this time, is a smarter manner using an Imputer to populate missing values for us
xmissing = dfclean[['jailprison' ,'Total number of calls',
'Total duration of calls',
'Total incoming calls',
'Total outgoing calls',
'Total number of missed calls',
'Total number of incoming calls, excluding missed',
'Proportion of incoming calls answered',
'Proportion of calls incoming',
'Duration of incoming calls',
'Duration of outgoing calls',
'Total number of night calls',
'Any night call',
'Number of incoming calls at night',
'Number of outgoing calls at night',
'Any night incoming call',
'Any night outgoing call',
'Min days between calls',
'Max days between calls',
'Total number of texts',
'Any night text',
'Number of texts at night',
'Min days between texts',
'Max days between texts']].values
# dfRawFilled = pandas.DataFrame(data=xdata)
imp = Imputer()
xdataimputed = imp.fit_transform(xmissing)
# imp.transform(dfRawFilled.values)
# dfRawFilled = pandas.DataFrame(data=(imp.transform(dfRawFilled.values)))
# dfRawFilled
xdataimputed

In [ ]:
xdataimputed.shape

In [ ]:
# We implement a random 80/20 split of the data to be used for train/test
# namimg variables that will be used for training/testing
xtrain = xdataimputed[train_indices]
xtest = xdataimputed[test_indices]

# ravel creates 1d array
y = dfclean[['close']].values.ravel()
ytrain = y[train_indices]
ytest = y[test_indices]

In [ ]:
# SVR

svr = SVR(kernel='rbf', C=1e1, epsilon=0.2)
svr.fit(xtrain, ytrain)
yhatsvr = svr.predict(xtest)
yhatsvr

In [ ]:
# NOT SURE WHERE THE ERROR HERE IS
lCs = []
train_err = []
test_err = []

for lC in range(-2,5): #[1,2,3,4,5,10,20,50]: range(1,30)
    svr = SVR(kernel='rbf', C=pow(10,lC)).fit(xtrain,ytrain)
    lCs.append(lC)
    train_err.append(mean_squared_error(ytrain, svr.predict(xtrain)))
    test_err.append(mean_squared_error(ytest, svr.predict(xtest)))
    
plt.plot(lCs, train_err, label="Train")
plt.plot(lCs, test_err, label="Test")
plt.legend()

In [ ]:
svr = SVR(kernel='rbf', C=1e2).fit(xtrain,ytrain)
plt.hist(svr.predict(xtest), label="Predicted")
plt.hist(ytest, label="True")
plt.legend()

In [ ]:
plt.scatter(ytrain, svr.predict(xtrain), label="Train")
plt.scatter(ytest, svr.predict(xtest), label="Test")
plt.legend()

In [ ]:
# MLPRegressor
mlp = MLPRegressor(solver='lbfgs', hidden_layer_sizes=(5,2))
mlp.fit(xtrain, ytrain)

In [ ]:
yhat = mlp.predict(xtest)
mean_squared_error(ytest, mlp.predict(xtest))

In [ ]:
plt.hist(yhat)

In [ ]:
hs = []
train_err = []
test_err = []

for h in range(5,55,3): #[1,2,3,4,5,10,20,50]: range(1,30)
    mlp = MLPRegressor(solver='lbfgs', hidden_layer_sizes=(h,5))
    mlp.fit(xtrain, ytrain)
    hs.append(h)
    train_err.append(mean_squared_error(ytrain, mlp.predict(xtrain)))
    test_err.append(mean_squared_error(ytest, mlp.predict(xtest)))
    
plt.plot(hs, train_err, label="Train")
plt.plot(hs, test_err, label="Test")
plt.legend()

In [ ]:
# We filter out the specific columns we are interested in

xdatafull = raw_data[['jailprison' ,'Total number of calls',
'Total duration of calls',
'Total incoming calls',
'Total outgoing calls',
'Total number of missed calls',
'Total number of incoming calls, excluding missed',
'Proportion of incoming calls answered',
'Proportion of calls incoming',
'Duration of incoming calls',
'Duration of outgoing calls',
'Total number of night calls',
'Any night call',
'Number of incoming calls at night',
'Number of outgoing calls at night',
'Any night incoming call',
'Any night outgoing call',
'Min days between calls',
'Max days between calls',
'Total number of texts',
'Any night text',
'Number of texts at night',
'Min days between texts',
'Max days between texts']].values

In [ ]:
dfRawFilledFull = pandas.DataFrame(data=xdatafull)

In [ ]:
imp = Imputer()
imp.fit(dfRawFilledFull)
imp.transform(dfRawFilledFull.values)
dfRawFilledFull = pandas.DataFrame(data=(imp.transform(dfRawFilledFull.values)))
dfRawFilledFull

In [ ]:
# update x to use values that have been populated now
xdatafullColumns = dfRawFilledFull[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22, 23]].values

In [ ]:
# debugging
xdatafullColumns

In [ ]:
GBregressor = GradientBoostingRegressor().fit(xtrain,ytrain)
yhatRegressor = GBregressor.predict(xdatafullColumns)
yhatRegressor
# Do one last final predict on best results and feed out 
raw_data['Predicted Closeness'] = yhatRegressor
raw_data

In [ ]:
# Finally we write out the new dataFrame with the "Predicted Closeness" column

dfPredictions = raw_data.to_csv('Closeness_Predictions.csv', encoding="utf-8")